<?php
namespace app\models;
use Yii;
use app\config\Vhelper;
class PurchaseCompact extends \yii\db\ActiveRecord
{
    public $orders;

    public static function tableName()
    {
        return '{{%purchase_compact}}';
    }

    public function formName()
    {
        return ''; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [[
                'j_company_name',
                'j_address',
                'j_linkman',
                'j_phone',
                'y_company_name',
                'y_address',
                'y_linkman',
                'y_phone',
                'ship_method',
                'shouhuo_address',
                'payment_explain',
                'hezuo_reqiure',
                'huikuan_information',
                'heyue_require',
                'zhijian_require',
                'settlement_ratio',
                'product_money',
                'real_money',
            ], 'required'],

            [[
                'compact_number',
                'supplier_name',
                'supplier_code',
                'source',
                'note_freight',
                'note_other',
                'compact_status',
                'payment_status',
                'refund_status',
                'create_time',
                'create_person_name',
                'create_person_id',
                'audit_time',
                'audit_person_name',
                'audit_person_id',
                'audit_note',
                'payment_time',
                'payment_person_name',
                'payment_person_id',
                'payment_note',
                'dj_money',
                'wk_money',
                'wk_total_money',
                'freight',
                'discount',
                'tpl_id',
                'is_drawback',
                'y_corporate',
                'j_email',
                'y_email',
                'baozhuang_require',
                'shouhou_clause',
                'buchong_clause',
                'djhuo_require',
            ], 'safe']

        ];
    }

    public function attributeLabels()
    {
        return [
            'compact_number' => '合同编号',
            'source' => '采购来源',
            'j_company_name' => '甲方公司名称',
            'j_address' => '甲方地址',
            'j_linkman' => '甲方联系人',
            'j_phone' => '甲方电话',
            'y_company_name' => '乙方公司名称',
            'y_address' => '乙方地址',
            'y_linkman' => '乙方联系人',
            'y_phone' => '乙方电话',
            'ship_method' => '运输方式',
            'shouhuo_address' => '收货地址',
            'payment_explain' => '付款说明',
            'hezuo_reqiure' => '合作要求',
            'huikuan_information' => '汇款信息',
            'heyue_require' => '合约要求',
            'zhijian_require' => '质检要求',
            'settlement_ratio' => '支付比例',
            'product_money' => '合同总商品金额',
            'freight' => '合同总运费',
            'discount' => '合同总优惠额',
            'real_money' => '合同实际总额',
        ];
    }

    public function getPurchaseCompactItems()
    {
        return $this->hasMany(PurchaseCompactItems::className(), ['compact_number' => 'compact_number'])->where(['bind' => 1]);
    }

    public function getPurchaseCompactPay()
    {
        return $this->hasMany(PurchaseOrderPay::className(), ['pur_number' => 'compact_number']);
    }

    public static function getPurNumbers($compact_number)
    {
        if (!is_array($compact_number)) {
            $compact_number = [$compact_number];
        }
        $pos = PurchaseCompactItems::find()
            ->select('pur_number')
            ->where(['in','compact_number',$compact_number])
            ->andwhere(['bind'=>1])
            ->column();
        return $pos;
    }

    // download compact payform
    public static function downloadCompactPayForm($control, $model)
    {
        $cpn = $model->compact_number;
        $models = PurchasePayForm::find()->where(['compact_number' => $cpn])->one();
        if(empty($data)) {
            return null;
        }
        foreach($models as $model) {
            $tpl = Template::findOne($data->tpl_id);
            $tplPath = $tpl->style_code;
            $content = $control->renderPartial("//template/tpls/{$tplPath}", ['model' => $model, 'print' => true]);
            self::output($content, $cpn, $model->id);
        }
        $dir = Yii::getAlias('@runtime/pdf/'.$cpn);
        return $dir;
    }

    // compress dir
    public static function compressDir($dir, $zip, $prev='.')
    {
        $handler = opendir($dir);
        $basename = basename($dir);
        $zip->addEmptyDir($prev . '/' . $basename);
        while($file = readdir($handler)) {
            $realpath = $dir . '/' . $file;
            if(is_dir($realpath)) {
                if($file !== '.' && $file !== '..') {
                    $zip->addEmptyDir($prev . '/' . $basename . '/' . $file);
                    self::compressDir($realpath, $zip, $prev . '/' . $basename);
                }
            } else {
                $zip->addFile($realpath, $prev. '/' . $basename . '/' . $file);
            }
        }
        closedir($handler);
        return null;
    }

    public static function output($content, $cpn, $filename=null)
    {
        $mpdf = new \mPDF();
        $mpdf->autoScriptToLang = 1;
        $mpdf->autoLangToFont = 1;
        $mpdf->SetDisplayMode(100);

        // 不要显示水印
        /*$mpdf->watermark_font = 'GB';
        $mpdf->SetWatermarkText('易佰网络科技',0.1);
        $mpdf->showWatermarkText = true;
        $mpdf->shrink_tables_to_fit = 1;*/
        
        if(is_null($filename)) {
            $file = $cpn.'.pdf';
        } else {
            $file = $filename.'.pdf';
        }
        $css = './css/mypdf.css';
        $style = file_get_contents($css);
        $mpdf->WriteHTML($style, 1);
        $mpdf->WriteHTML($content, 2);
        $mpdf->Output($file,'d');
    }

    public static function getPayFormContent($pay_id)
    {
        $model = PurchasePayForm::find()->where(['pay_id' => $pay_id])->one();
        if(empty($model)) {
            return null;
        }
        $tpl = Template::findOne($model->tpl_id);
        $tplPath = $tpl->style_code;
        return [
            'tpl' => "//template/tpls/{$tplPath}",
            'data' => ['model' => $model, 'print' => true]
        ];
    }

    /**
     * 得到合同支付计划（最高3段）
     * $param obj $is_drawback 是否含税（默认不含税）1不含税 2含税
     * @param string $ratio 合同的结算比例 '30%+30%+40%'
     * @param float $productMoney 合同的总产品额
     * @param float $freight 合同的总运费
     * @param float $discount 合同的总优惠额
     * @param int $is_drawback 是否退税（默认不退税）
     * @return array 返回订金，中款，尾款信息
     */
    public static function PaymentPlan3($ratio, $productMoney, $freight, $discount, $is_drawback = 1)
    {
        $_ratio = explode('+', $ratio);
        $dj = 0;
        $wk = 0;
        $wwk = 0;

        if($is_drawback == 2) { // 含税（对公）
            if(count($_ratio) > 1) {
                if(count($_ratio) == 2) {
                    $djRatio = $_ratio[0];
                    $wkRatio = $_ratio[1];
                    $dj = ($productMoney*(int)$djRatio)/100 - $discount;  // 订金 = 产品总额*首款百分比-优惠
                    $wk = ($productMoney*(int)$wkRatio)/100; // 尾款
                    $wwk = $wk;
                } else if(count($_ratio) == 3) {
                    $djRatio = $_ratio[0];
                    $wkRatio = $_ratio[1];
                    $wwkRatio = 100-(int)$djRatio-(int)$wkRatio;
                    $dj = ($productMoney*(int)$djRatio)/100 - $discount; // 订金除去优惠额
                    $wk = ($productMoney*(int)$wkRatio)/100;   // 中款
                    $wwk = ($productMoney*(int)$wwkRatio)/100; // 尾款
                } else if(count($_ratio) > 3) {
                    exit('目前暂不支持大于3次的结算比例');
                }
            }
        } else { // 不含税（对私）
            if(count($_ratio) > 1) {
                if(count($_ratio) == 2) {
                    $djRatio = $_ratio[0];
                    $wkRatio = $_ratio[1];
                    $dj = ($productMoney*(int)$djRatio)/100 - $discount;  // 订金 = 产品总额*首款百分比-优惠
                    $wk = ($productMoney*(int)$wkRatio)/100;   // 尾款 = 产品总额*尾款百分比
                    $wwk = $wk + $freight; // 尾款总额 = 产品总额*尾款百分比 + 运费
                } else if(count($_ratio) == 3) {
                    $djRatio = $_ratio[0];
                    $wkRatio = $_ratio[1];
                    $wwkRatio = 100-(int)$djRatio-(int)$wkRatio;
                    $dj = ($productMoney*(int)$djRatio)/100 - $discount; // 订金除去优惠额
                    $wk = ($productMoney*(int)$wkRatio)/100; // 中款不含运费与优惠
                    $wwk = ($productMoney*(int)$wwkRatio)/100 + $freight; // 尾款含运费
                } else if(count($_ratio) > 3) {
                    exit('目前暂不支持大于3次的结算比例');
                }
            }
        }
        return [
            'dj' => $dj,
            'wk' => $wk,
            'wwk' => $wwk
        ];
    }


    /**
     * 得到合同请款选项列表（最高3段）
     * @param obj $model 合同模型
     * @return array 返回选项列表
     */
    public static function PaymentSelect3($model)
    {
        if(empty($model->settlement_ratio)) {
            return false;
        }
        $js_ratio = explode('+', $model->settlement_ratio);
        $select_ratio = [];
        if(count($js_ratio) == 1) {
            $select_ratio[] = ['ratio' => $js_ratio[0], 'money' => $model->real_money, 'pay_category' => 11];
        } else if(count($js_ratio) == 2) {
            $select_ratio[] = ['ratio' => $js_ratio[0], 'money' => $model->dj_money, 'pay_category' => 12];
            $select_ratio[] = ['ratio' => $js_ratio[1], 'money' => $model->wk_total_money, 'pay_category' => 20];
        } else if(count($js_ratio) == 3) {
            $select_ratio[] = ['ratio' => $js_ratio[0], 'money' => $model->dj_money, 'pay_category' => 12];
            $select_ratio[] = ['ratio' => $js_ratio[1], 'money' => $model->wk_money, 'pay_category' => 13];
            $select_ratio[] = ['ratio' => $js_ratio[2], 'money' => $model->wk_total_money, 'pay_category' => 20];
        } else if(count($js_ratio) > 3) {
            exit('目前暂不支持大于3次的结算比例');
        }
        // 含税的合同，加上运费选择列，可以直接请运费
        if($model->is_drawback == 2) {
            $select_ratio[] = ['ratio' => '运费', 'money' => $model->freight, 'pay_category' => 10];
        }
        return $select_ratio;
    }

    /**
     * 检测采购单是否存在绑定关系
     */
    public static function is_bind($opn)
    {
        $has = self::find()
            ->from('pur_purchase_compact_items')
            ->where(['pur_number' => $opn, 'bind' => 1])->one();
        if(empty($has)) {
            return false;
        } else {
            return $has->compact_number;
        }
    }


}
